import { LegalPage } from "@/components/legal/legal-page";
import { getLegalOperator } from "@/lib/legal";

export const metadata = { title: "Datenschutzerklärung" };
export const dynamic = "force-dynamic";

export default function PrivacyPage() {
  const operator = getLegalOperator();
  return (
    <LegalPage title="Datenschutzerklärung" updated="27. August 2026" operator={operator}>
      <section><h2>1. Verantwortlicher</h2><address>{operator.name}<br />{operator.street}<br />{operator.postalCode} {operator.city}<br />{operator.country}<br />Datenschutzkontakt: <a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a>{operator.dataProtectionOfficer ? <><br />Datenschutzbeauftragte Stelle: {operator.dataProtectionOfficer}</> : null}</address></section>
      <section><h2>2. Zweck und Umfang</h2><p>Diese Erklärung informiert nach Art. 13 und 14 DSGVO über die Verarbeitung personenbezogener Daten bei Nutzung der Nexus-Webseite, des Dashboards, der API und des Discord-Bots.</p></section>
      <section><h2>3. Verarbeitete Daten</h2><ul><li>Discord-Konto: Nutzer-ID, Benutzer- und Anzeigename, Avatar, Sprache, OAuth-Berechtigungen und verschlüsselte Zugriffstoken.</li><li>Serverdaten: Server-, Kanal-, Rollen- und Berechtigungskennungen sowie aktivierte Module und Konfigurationen.</li><li>Bot-Ereignisse: nur die für aktivierte Funktionen erforderlichen Mitglieds-, Nachrichten-, Reaktions-, Sprach- und Moderationsereignisse.</li><li>Funktionsdaten: Moderationsfälle, Warnungen, Verifizierungen, Tickets, Vorschläge, XP-, Erinnerungs- und Integrationsdaten.</li><li>Betriebsdaten: IP-Adresse, Zeitstempel, Request-ID, Sicherheits-, Audit-, Fehler- und Nutzungsmetriken. Befehlsargumente mit sensiblen Inhalten werden nicht allgemein für Analytics gespeichert.</li><li>Dateien: ausdrücklich hochgeladene Willkommensbilder, Ticketanhänge oder sonstige konfigurierte Assets.</li></ul></section>
      <section><h2>4. Zwecke und Rechtsgrundlagen</h2><ul><li>Bereitstellung, Authentifizierung, Konfiguration und Ausführung von Nexus: Art. 6 Abs. 1 lit. b DSGVO.</li><li>Serverseitige Moderation, Sicherheitsprotokolle, Missbrauchsabwehr und stabiler Betrieb: Art. 6 Abs. 1 lit. f DSGVO; berechtigtes Interesse ist der sichere und nachvollziehbare Betrieb.</li><li>Erfüllung gesetzlicher Aufbewahrungs-, Auskunfts- oder Sicherheitsverpflichtungen: Art. 6 Abs. 1 lit. c DSGVO.</li><li>Optionale Integrationen oder nicht notwendige Technologien: Art. 6 Abs. 1 lit. a DSGVO, soweit eine Einwilligung erforderlich ist.</li></ul></section>
      <section><h2>5. Rollen der Discord-Serverbetreiber</h2><p>Serverbetreiber entscheiden über Aktivierung, Zweck und Konfiguration vieler Nexus-Funktionen und können insoweit eigene datenschutzrechtliche Verantwortlichkeit tragen. Sie müssen ihre Mitglieder transparent informieren, nur erforderliche Funktionen aktivieren und Lösch- sowie Auskunftsanfragen berücksichtigen.</p></section>
      <section><h2>6. Empfänger und Auftragsverarbeiter</h2><p>Daten werden nur soweit erforderlich an Hosting- und Infrastrukturpartner übermittelt: Supabase für Datenbank, Authentifizierung, Realtime und Storage; Vercel für das Dashboard; Render für Bot, API und Worker; Discord für OAuth und Bot-Aktionen. Optionale Twitch-, YouTube-, Minecraft- oder Crafty-Verbindungen werden nur bei Aktivierung genutzt. Eine aktuelle Unterauftragnehmerliste und ergänzende Kontaktdaten werden auf Anfrage bereitgestellt.</p></section>
      <section><h2>7. Drittlandübermittlungen</h2><p>Einzelne Anbieter können Daten außerhalb des Europäischen Wirtschaftsraums verarbeiten. Übermittlungen erfolgen nur auf Grundlage eines Angemessenheitsbeschlusses, geeigneter Garantien wie EU-Standardvertragsklauseln oder einer anderen gesetzlichen Ausnahme. Die konkret gewählte Hosting-Region wird nach Möglichkeit innerhalb der EU festgelegt.</p></section>
      <section><h2>8. Speicherdauer</h2><p>Konfigurationen bleiben während der Installation gespeichert. Nach Verlassen eines Servers werden Daten standardmäßig 30 Tage zur Wiederherstellung gesperrt und anschließend gelöscht; der Serverbetreiber kann sofortige Löschung wählen. OAuth-Verknüpfungen werden bei Kontolöschung entfernt. Sicherheits- und Auditdaten werden grundsätzlich höchstens 90 Tage, aggregierte nicht personenbezogene Metriken länger gespeichert. Gesetzliche Pflichten und laufende Rechtsverteidigung können abweichende Fristen erfordern.</p></section>
      <section><h2>9. Cookies und lokale Speicherung</h2><p>Nexus verwendet notwendige, sichere Cookies für Anmeldung, Sitzungsaktualisierung, OAuth-Zustand, Sprache, Theme und Navigation. Diese sind für den ausdrücklich gewünschten digitalen Dienst erforderlich. Nicht notwendige Analyse- oder Werbe-Cookies werden nicht eingesetzt. Sollte sich dies ändern, erfolgt eine vorherige Einwilligungsabfrage gemäß DSGVO und § 25 TDDDG.</p></section>
      <section><h2>10. Automatisierte Entscheidungen</h2><p>AutoMod und Anti-Raid können anhand vom Serverbetreiber festgelegter Regeln Inhalte löschen, Warnungen erstellen oder zeitlich begrenzte Maßnahmen auslösen. Nexus setzt keine ausschließlich auf schwachen Heuristiken beruhenden automatischen Massenbanns ein. Eine rechtliche oder vergleichbar erhebliche Entscheidung im Sinne von Art. 22 DSGVO ist nicht beabsichtigt; Serveradministratoren können Maßnahmen prüfen und korrigieren.</p></section>
      <section><h2>11. Sicherheit</h2><p>Wir setzen Transportverschlüsselung, verschlüsselte OAuth-Token, Zugriffskontrollen, Row Level Security, minimierte Bot-Berechtigungen, Audit-Protokolle, Rate-Limits, signierte Webhooks und regelmäßige Sicherheitsprüfungen ein. Absolute Sicherheit kann technisch nicht garantiert werden.</p></section>
      <section><h2>12. Rechte betroffener Personen</h2><p>Betroffene Personen haben nach Maßgabe der gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Einwilligungen können jederzeit mit Wirkung für die Zukunft widerrufen werden. Anfragen sind an <a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a> zu richten. Zur Vermeidung unbefugter Offenlegung kann ein Identitätsnachweis erforderlich sein.</p></section>
      <section><h2>13. Beschwerderecht</h2><p>Betroffene Personen können sich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere in dem Mitgliedstaat ihres Aufenthaltsorts, Arbeitsplatzes oder des vermuteten Verstoßes.</p></section>
      <section><h2>14. Pflicht zur Bereitstellung</h2><p>Discord-Kennung, Authentifizierungs- und notwendige Serverdaten werden für die Nutzung benötigt. Ohne diese Daten können Dashboard und Bot nicht bereitgestellt werden. Optionale Integrationsdaten sind freiwillig; das jeweilige Modul bleibt ohne sie deaktiviert.</p></section>
      <section><h2>15. Änderungen</h2><p>Wir aktualisieren diese Erklärung bei Änderungen der Verarbeitung oder Rechtslage. Das Datum der letzten Änderung wird oben angegeben; wesentliche Änderungen werden angemessen hervorgehoben.</p></section>
    </LegalPage>
  );
}
