import { LegalPage } from "@/components/legal/legal-page";
import { getLegalOperator } from "@/lib/legal";

export const metadata = { title: "Nutzungsbedingungen" };
export const dynamic = "force-dynamic";

export default function TermsPage() {
  const operator = getLegalOperator();
  return (
    <LegalPage title="Nutzungsbedingungen" updated="27. August 2026">
      <section><h2>1. Anbieter und Geltungsbereich</h2><p>Diese Nutzungsbedingungen gelten für die Nutzung der Discord-Anwendung, des Bots, des Dashboards und der zugehörigen Schnittstellen „Nexus“ durch Serverinhaber, Administratoren und sonstige berechtigte Nutzer.</p><address>{operator.name}<br />{operator.street}<br />{operator.postalCode} {operator.city}<br />{operator.country}<br />E-Mail: <a href={`mailto:${operator.email}`}>{operator.email}</a>{operator.representative ? <><br />Vertretungsberechtigt: {operator.representative}</> : null}</address></section>
      <section><h2>2. Vertragsschluss und Berechtigung</h2><p>Der Nutzungsvertrag kommt zustande, wenn eine berechtigte Person Nexus über Discord autorisiert oder das Dashboard erstmals für einen Discord-Server verwendet. Die handelnde Person bestätigt, mindestens 18 Jahre alt oder nach dem anwendbaren Recht wirksam handlungsfähig zu sein und zur Verwaltung des ausgewählten Servers befugt zu sein.</p></section>
      <section><h2>3. Leistungsumfang</h2><p>Nexus stellt konfigurierbare Funktionen für Moderation, Verifizierung, Protokollierung, Community-Verwaltung und optionale Integrationen bereit. Verfügbare Module, Reifegrade und technische Voraussetzungen werden im Dashboard angezeigt. Beta- und experimentelle Funktionen können sich ändern oder vorübergehend eingeschränkt sein.</p><p>Discord, Twitch, YouTube, Supabase, Vercel und Koyeb sind eigenständige Drittanbieter. Deren Verfügbarkeit und Bedingungen liegen außerhalb unseres Einflussbereichs.</p></section>
      <section><h2>4. Pflichten der Serveradministratoren</h2><p>Administratoren müssen Nexus nur mit erforderlichen Discord-Berechtigungen ausstatten, Rollen- und Kanalhierarchien prüfen, Mitglieder über den Einsatz des Bots informieren und für eine rechtmäßige Konfiguration sorgen. Insbesondere dürfen Moderations-, Protokollierungs- und Verifizierungsfunktionen nicht für rechtswidrige Überwachung, Diskriminierung oder Umgehung von Discord-Regeln eingesetzt werden.</p></section>
      <section><h2>5. Zulässige Nutzung</h2><p>Untersagt sind insbesondere Angriffe auf Nexus oder Dritte, Umgehung von Zugriffskontrollen oder Rate-Limits, automatisierte Massenanfragen außerhalb freigegebener Schnittstellen, Schadcode, rechtswidrige Inhalte, Identitätstäuschung, der Weiterverkauf nicht freigegebener Zugänge und jede Nutzung entgegen den Discord Developer Terms oder anwendbarem Recht.</p></section>
      <section><h2>6. Inhalte und Konfigurationen</h2><p>Nutzer behalten ihre Rechte an eingestellten Texten, Bildern, Vorlagen und Konfigurationen. Sie räumen uns die für Bereitstellung, Speicherung, Sicherung und Ausgabe innerhalb des gewählten Discord-Servers erforderlichen Nutzungsrechte ein. Nutzer sichern zu, dass sie die erforderlichen Rechte besitzen.</p></section>
      <section><h2>7. Moderationsentscheidungen</h2><p>Nexus unterstützt Moderationsentscheidungen technisch. Serveradministratoren bleiben für Regeln, Konfiguration und Prüfung von Maßnahmen verantwortlich. Schwache Anti-Raid-Heuristiken führen nicht zu automatischen Massenbanns. Sicherheitskritische Automatisierungen müssen regelmäßig kontrolliert werden.</p></section>
      <section><h2>8. Verfügbarkeit und Änderungen</h2><p>Wir bemühen uns um einen sicheren und zuverlässigen Betrieb, schulden jedoch keine ununterbrochene Verfügbarkeit, sofern nicht ausdrücklich anders vereinbart. Wartung, Sicherheitsmaßnahmen, Störungen bei Drittanbietern oder höhere Gewalt können zu Einschränkungen führen. Wesentliche nachteilige Änderungen werden mit angemessener Frist angekündigt, soweit Sicherheits- oder Rechtsgründe keine sofortige Änderung erfordern.</p></section>
      <section><h2>9. Sperrung und Beendigung</h2><p>Nutzer können Nexus jederzeit vom Server entfernen und die Kontoverknüpfung beenden. Wir dürfen Zugänge bei erheblichen oder wiederholten Verstößen, Sicherheitsrisiken oder rechtlichen Verpflichtungen vorübergehend sperren oder beenden. Soweit vertretbar, informieren wir zuvor und ermöglichen Stellungnahme oder Abhilfe.</p></section>
      <section><h2>10. Haftung</h2><p>Wir haften unbeschränkt bei Vorsatz, grober Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit, nach dem Produkthaftungsgesetz und im Umfang ausdrücklich übernommener Garantien. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den vorhersehbaren, vertragstypischen Schaden begrenzt. Im Übrigen ist die Haftung bei leichter Fahrlässigkeit ausgeschlossen. Gesetzlich zwingende Haftung bleibt unberührt.</p></section>
      <section><h2>11. Datenschutz</h2><p>Informationen zur Verarbeitung personenbezogener Daten enthält die <a href="/de/datenschutz">Datenschutzerklärung</a>.</p></section>
      <section><h2>12. Schlussbestimmungen</h2><p>Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Zwingende Verbraucherschutzvorschriften des gewöhnlichen Aufenthaltsstaats bleiben unberührt. Ist der Nutzer Kaufmann, juristische Person des öffentlichen Rechts oder öffentlich-rechtliches Sondervermögen, ist der Sitz des Anbieters Gerichtsstand. Die Unwirksamkeit einzelner Bestimmungen lässt die übrigen Bestimmungen unberührt.</p></section>
    </LegalPage>
  );
}
